import "./globals.css";
import type { Metadata } from "next";
import { AuthProvider } from "@/app/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col justify-between">
        <AuthProvider>
          <div className=" bg-[var(--color-background-main)] h-full ">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
